# Generated by Django 4.1.5 on 2023-06-28 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='comment',
        ),
    ]
