# Generated by Django 4.1.5 on 2023-06-28 14:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('show', '0002_delete_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='review',
            fields=[
                ('rev_id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField(max_length=100)),
                ('likes', models.IntegerField(default=0)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='show.movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
