# Generated by Django 4.1.5 on 2023-07-03 04:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0008_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='show',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='show.show'),
        ),
    ]
