# Generated by Django 4.1.5 on 2023-07-04 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0009_alter_booking_show'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='session',
        ),
    ]
