# Generated by Django 4.1.5 on 2023-07-04 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0012_remove_booking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='col_no',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='row_no',
            field=models.SmallIntegerField(),
        ),
    ]
