# Generated by Django 4.1.5 on 2023-07-04 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0013_alter_booking_col_no_alter_booking_row_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='col_no',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='row_no',
            field=models.PositiveIntegerField(),
        ),
    ]
