# Generated by Django 4.1.5 on 2023-07-04 11:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0014_alter_booking_col_no_alter_booking_row_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='col_no',
            field=models.PositiveSmallIntegerField(verbose_name=django.core.validators.MaxValueValidator(10)),
        ),
        migrations.AlterField(
            model_name='booking',
            name='row_no',
            field=models.PositiveSmallIntegerField(verbose_name=django.core.validators.MaxValueValidator(10)),
        ),
    ]
