# Generated by Django 4.1.5 on 2023-07-05 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0016_alter_booking_col_no_alter_booking_row_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='col_no',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='row_no',
        ),
        migrations.AddField(
            model_name='booking',
            name='num_ticket',
            field=models.PositiveSmallIntegerField(default=1, max_length=1),
        ),
        migrations.AddField(
            model_name='booking',
            name='seat_no',
            field=models.PositiveIntegerField(default=2, max_length=20),
        ),
    ]
