# Generated by Django 4.1.5 on 2023-07-05 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0017_remove_booking_col_no_remove_booking_row_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='seat_no',
            field=models.CharField(default=2, max_length=20),
        ),
    ]
