# Generated by Django 4.1.5 on 2023-07-08 21:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('show', '0020_booking_qr_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('Rating_id', models.AutoField(primary_key=True, serialize=False)),
                ('rate', models.IntegerField(default=0)),
                ('movie', models.ForeignKey(blank=True, default='2', on_delete=django.db.models.deletion.CASCADE, to='show.movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
